bash /root/user_monitoring_scripts/monitor_center_of_the_labyrinth.bash &
bash /root/user_monitoring_scripts/monitor_read.bash &
bash /root/user_monitoring_scripts/monitor_the.bash &
bash /root/user_monitoring_scripts/monitor_manual.bash &
bash /root/user_monitoring_scripts/monitor_git.bash &
bash /root/user_monitoring_scripts/monitor_analytical_engine.bash &
bash /root/user_monitoring_scripts/monitor_Z3.bash &
bash /root/user_monitoring_scripts/monitor_Bombe.bash &
bash /root/user_monitoring_scripts/monitor_Sir_Tim_Berners-Lee.bash &
bash /root/user_monitoring_scripts/monitor_IBM_704.bash &
bash /root/user_monitoring_scripts/monitor_Tide-predicting_machine.bash &
bash /root/user_monitoring_scripts/monitor_Harrison_s_Chronometer.bash &
bash /root/user_monitoring_scripts/monitor_Antikythera_mechanism.bash &
bash /root/user_monitoring_scripts/monitor_abacus.bash &
bash /root/user_monitoring_scripts/monitor_inception.bash &
